class Country < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'アルジェリア' },
    { id: 3, name: 'アンゴラ' },
    { id: 4, name: 'ウガンダ' },
    { id: 5, name: 'エジプト' },
    { id: 6, name: 'エスワティニ' },
    { id: 7, name: 'エチオピア' },
    { id: 8, name: 'エリトリア' },
    { id: 9, name: 'ガーナ' },
    { id: 10, name: 'カーボベルデ' },
    { id: 11, name: 'ガボン' },
    { id: 12, name: 'カメルーン' },
    { id: 13, name: 'ガンビア' },
    { id: 14, name: 'ギニア' },
    { id: 15, name: 'ギニアビサウ' },
    { id: 16, name: 'ケニア' },
    { id: 17, name: 'コートジボワール' },
    { id: 18, name: 'コモロ' },
    { id: 19, name: 'コンゴ共和国' },
    { id: 20, name: 'コンゴ民主共和国' },
    { id: 21, name: 'サントメ・プリンシペ' },
    { id: 22, name: 'ザンビア' },
    { id: 23, name: 'シエラレオネ' },
    { id: 24, name: 'ジブチ' },
    { id: 25, name: 'ジンバブエ' },
    { id: 26, name: 'スーダン' },
    { id: 27, name: 'セーシェル' },
    { id: 28, name: '赤道ギニア' },
    { id: 29, name: 'セネガル' },
    { id: 30, name: 'ソマリア' },
    { id: 31, name: 'タンザニア' },
    { id: 32, name: 'チャド' },
    { id: 33, name: '中央アフリカ' },
    { id: 34, name: 'チュニジア' },
    { id: 35, name: 'トーゴ' },
    { id: 36, name: 'ナイジェリア' },
    { id: 37, name: 'ナミビア' },
    { id: 38, name: 'ニジェール' },
    { id: 39, name: 'ブルキナファソ' },
    { id: 40, name: 'ブルンジ' },
    { id: 41, name: 'ベナン' },
    { id: 42, name: 'ボツワナ' },
    { id: 43, name: 'マダガスカル' },
    { id: 44, name: 'マラウイ' },
    { id: 45, name: 'マリ' },
    { id: 46, name: '南アフリカ' },
    { id: 47, name: '南スーダン' },
    { id: 48, name: 'モザンビーク' },
    { id: 49, name: 'モーリシャス' },
    { id: 50, name: 'モーリタニア' },
    { id: 51, name: 'モロッコ' },
    { id: 52, name: 'リビア' },
    { id: 53, name: 'リベリア' },
    { id: 54, name: 'ルワンダ' },
    { id: 55, name: 'レソト' }
  ]

  include ActiveHash::Associations
  has_many :posts
end
